interface TAlbum {
  albumName: string;
  artist: string;
  genre: string;
  country: string;
  yandexMusicPlays: number;
  soundcloudPlays: number;
  rhymesImages: number;
  structureRhythm: number;
  styleImplementation: number;
  individualityCharisma: number;
  atmosphereVibe: number;
}

const albums: TAlbum[] = [
  {
    albumName: "flexyswag",
    artist: "madk1d",
    genre: "архивкор",
    country: "Россия",
    yandexMusicPlays: 453481,
    soundcloudPlays: 19849,
    rhymesImages: 0,
    structureRhythm: 6,
    styleImplementation: 1,
    individualityCharisma: 0,
    atmosphereVibe: 5
  },
  {
    albumName: "Он сказал поехали!",
    artist: "madk1d",
    genre: "архивкор",
    country: "Россия",
    yandexMusicPlays: 150136,
    soundcloudPlays: 160998,
    rhymesImages: 6,
    structureRhythm: 3,
    styleImplementation: 9,
    individualityCharisma: 8,
    atmosphereVibe: 8
  },
  {
    albumName: "Мрачные треды",
    artist: "тёмный принц",
    genre: "архивкор",
    country: "Россия",
    yandexMusicPlays: 85185,
    soundcloudPlays: 102271,
    rhymesImages: 4,
    structureRhythm: 3,
    styleImplementation: 10,
    individualityCharisma: 10,
    atmosphereVibe: 2
  },
  {
    albumName: "defect (EP)",
    artist: "greyrock",
    genre: "архивкор",
    country: "Россия",
    yandexMusicPlays: 355803,
    soundcloudPlays: 127377,
    rhymesImages: 8,
    structureRhythm: 3,
    styleImplementation: 7,
    individualityCharisma: 2,
    atmosphereVibe: 7
  },
  {
    albumName: "Project n(o)va",
    artist: "FORTUNA 812",
    genre: "архивкор;дарк треп",
    country: "Россия",
    yandexMusicPlays: 42022,
    soundcloudPlays: 480645,
    rhymesImages: 5,
    structureRhythm: 8,
    styleImplementation: 1,
    individualityCharisma: 3,
    atmosphereVibe: 0
  },
  {
    albumName: "basedgod",
    artist: "FORTUNA 812",
    genre: "архивкор;дарк треп",
    country: "Россия",
    yandexMusicPlays: 43536,
    soundcloudPlays: 32810,
    rhymesImages: 8,
    structureRhythm: 9,
    styleImplementation: 9,
    individualityCharisma: 1,
    atmosphereVibe: 10
  },
  {
    albumName: "саундклауд пак",
    artist: "урал гайсин",
    genre: "архивкор",
    country: "Казахстан",
    yandexMusicPlays: 199560,
    soundcloudPlays: 179544,
    rhymesImages: 9,
    structureRhythm: 3,
    styleImplementation: 9,
    individualityCharisma: 6,
    atmosphereVibe: 1
  },
  {
    albumName: "я истекаю кровью (EP)",
    artist: "урал гайсин",
    genre: "архивкор",
    country: "Казахстан",
    yandexMusicPlays: 147277,
    soundcloudPlays: 203764,
    rhymesImages: 10,
    structureRhythm: 9,
    styleImplementation: 5,
    individualityCharisma: 2,
    atmosphereVibe: 2
  },
  {
    albumName: "GOD SYSTEM",
    artist: "Kai Angel",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 318863,
    soundcloudPlays: 55924,
    rhymesImages: 2,
    structureRhythm: 1,
    styleImplementation: 10,
    individualityCharisma: 7,
    atmosphereVibe: 5
  },
  {
    albumName: "Angel May Cry 2",
    artist: "Kai Angel",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 361752,
    soundcloudPlays: 377397,
    rhymesImages: 9,
    structureRhythm: 4,
    styleImplementation: 0,
    individualityCharisma: 2,
    atmosphereVibe: 2
  },
  {
    albumName: "Angel May Cry",
    artist: "Kai Angel",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 128695,
    soundcloudPlays: 44076,
    rhymesImages: 8,
    structureRhythm: 4,
    styleImplementation: 6,
    individualityCharisma: 2,
    atmosphereVibe: 8
  },
  {
    albumName: "damage",
    artist: "Kai Angel",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 117928,
    soundcloudPlays: 491884,
    rhymesImages: 1,
    structureRhythm: 7,
    styleImplementation: 6,
    individualityCharisma: 5,
    atmosphereVibe: 0
  },
  {
    albumName: "immortal",
    artist: "Kai Angel",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 281762,
    soundcloudPlays: 447440,
    rhymesImages: 8,
    structureRhythm: 4,
    styleImplementation: 4,
    individualityCharisma: 6,
    atmosphereVibe: 5
  },
  {
    albumName: "MARILYN MANSON",
    artist: "Kai Angel",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 169641,
    soundcloudPlays: 96498,
    rhymesImages: 1,
    structureRhythm: 10,
    styleImplementation: 10,
    individualityCharisma: 5,
    atmosphereVibe: 8
  },
  {
    albumName: "kAiCoRe",
    artist: "Kai Angel",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 170396,
    soundcloudPlays: 331501,
    rhymesImages: 2,
    structureRhythm: 10,
    styleImplementation: 5,
    individualityCharisma: 0,
    atmosphereVibe: 5
  },
  {
    albumName: "Heavy Metal 2",
    artist: "Kai Angel  & 9mice",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 312133,
    soundcloudPlays: 81614,
    rhymesImages: 2,
    structureRhythm: 10,
    styleImplementation: 6,
    individualityCharisma: 9,
    atmosphereVibe: 3
  },
  {
    albumName: "Heavy Metal",
    artist: "Kai Angel  & 9mice",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 221762,
    soundcloudPlays: 71701,
    rhymesImages: 7,
    structureRhythm: 0,
    styleImplementation: 10,
    individualityCharisma: 5,
    atmosphereVibe: 10
  },
  {
    albumName: "ORPHEUS",
    artist: "9mice",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 98436,
    soundcloudPlays: 312677,
    rhymesImages: 3,
    structureRhythm: 9,
    styleImplementation: 5,
    individualityCharisma: 10,
    atmosphereVibe: 2
  },
  {
    albumName: "ASPHALT",
    artist: "9mice",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 49991,
    soundcloudPlays: 28791,
    rhymesImages: 8,
    structureRhythm: 1,
    styleImplementation: 3,
    individualityCharisma: 5,
    atmosphereVibe: 2
  },
  {
    albumName: "9MM",
    artist: "9mice",
    genre: "viperr;opium",
    country: "США",
    yandexMusicPlays: 204353,
    soundcloudPlays: 381481,
    rhymesImages: 3,
    structureRhythm: 1,
    styleImplementation: 9,
    individualityCharisma: 0,
    atmosphereVibe: 5
  },
  {
    albumName: "Fluddality",
    artist: "GONE.Fludd",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 347773,
    soundcloudPlays: 477934,
    rhymesImages: 0,
    structureRhythm: 7,
    styleImplementation: 1,
    individualityCharisma: 3,
    atmosphereVibe: 9
  },
  {
    albumName: "BOYS DON'T CRY",
    artist: "GONE.Fludd",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 46492,
    soundcloudPlays: 255316,
    rhymesImages: 6,
    structureRhythm: 5,
    styleImplementation: 1,
    individualityCharisma: 5,
    atmosphereVibe: 10
  },
  {
    albumName: "СУПЕРЧУИТС",
    artist: "GONE.Fludd",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 191387,
    soundcloudPlays: 292274,
    rhymesImages: 7,
    structureRhythm: 0,
    styleImplementation: 9,
    individualityCharisma: 1,
    atmosphereVibe: 1
  },
  {
    albumName: "VOODOO CHILD",
    artist: "GONE.Fludd",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 399455,
    soundcloudPlays: 110761,
    rhymesImages: 4,
    structureRhythm: 0,
    styleImplementation: 9,
    individualityCharisma: 1,
    atmosphereVibe: 9
  },
  {
    albumName: "DIGITAL FANTAZY",
    artist: "GONE.Fludd",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 334482,
    soundcloudPlays: 126117,
    rhymesImages: 8,
    structureRhythm: 8,
    styleImplementation: 2,
    individualityCharisma: 1,
    atmosphereVibe: 7
  },
  {
    albumName: "Pink Phloyd",
    artist: "Pharaoh",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 489973,
    soundcloudPlays: 300887,
    rhymesImages: 1,
    structureRhythm: 3,
    styleImplementation: 8,
    individualityCharisma: 7,
    atmosphereVibe: 4
  },
  {
    albumName: "Плакшери",
    artist: "Pharaoh",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 116558,
    soundcloudPlays: 468148,
    rhymesImages: 7,
    structureRhythm: 4,
    styleImplementation: 7,
    individualityCharisma: 7,
    atmosphereVibe: 3
  },
  {
    albumName: "Платина",
    artist: "Платина",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 25115,
    soundcloudPlays: 303392,
    rhymesImages: 8,
    structureRhythm: 3,
    styleImplementation: 7,
    individualityCharisma: 9,
    atmosphereVibe: 2
  },
  {
    albumName: "Опиаты Круг",
    artist: "Платина",
    genre: "хип-хоп;рэп;рнб",
    country: "Россия",
    yandexMusicPlays: 276927,
    soundcloudPlays: 235798,
    rhymesImages: 7,
    structureRhythm: 3,
    styleImplementation: 7,
    individualityCharisma: 5,
    atmosphereVibe: 6
  },
  {
    albumName: "Sosa Muzik",
    artist: "Платина",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 15088,
    soundcloudPlays: 199335,
    rhymesImages: 7,
    structureRhythm: 4,
    styleImplementation: 8,
    individualityCharisma: 4,
    atmosphereVibe: 7
  },
  {
    albumName: "Сладких снов",
    artist: "Платина",
    genre: "хип-хоп;рэп;рнб",
    country: "Россия",
    yandexMusicPlays: 25307,
    soundcloudPlays: 34026,
    rhymesImages: 10,
    structureRhythm: 2,
    styleImplementation: 0,
    individualityCharisma: 2,
    atmosphereVibe: 2
  },
  {
    albumName: "РНБ КЛУБ",
    artist: "Платина",
    genre: "хип-хоп;рэп;рнб",
    country: "Россия",
    yandexMusicPlays: 255099,
    soundcloudPlays: 86811,
    rhymesImages: 2,
    structureRhythm: 8,
    styleImplementation: 2,
    individualityCharisma: 7,
    atmosphereVibe: 2
  },
  {
    albumName: "Классика",
    artist: "Джон Гарик",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 24776,
    soundcloudPlays: 487448,
    rhymesImages: 1,
    structureRhythm: 8,
    styleImplementation: 0,
    individualityCharisma: 8,
    atmosphereVibe: 6
  },
  {
    albumName: "Шансун",
    artist: "Джон Гарик",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 333580,
    soundcloudPlays: 40038,
    rhymesImages: 7,
    structureRhythm: 0,
    styleImplementation: 3,
    individualityCharisma: 4,
    atmosphereVibe: 4
  },
  {
    albumName: "Ядик",
    artist: "Джон Гарик",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 45149,
    soundcloudPlays: 448389,
    rhymesImages: 4,
    structureRhythm: 3,
    styleImplementation: 10,
    individualityCharisma: 5,
    atmosphereVibe: 6
  },
  {
    albumName: "Never Broke Again",
    artist: "xxxmanera",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 440657,
    soundcloudPlays: 206481,
    rhymesImages: 10,
    structureRhythm: 10,
    styleImplementation: 4,
    individualityCharisma: 4,
    atmosphereVibe: 4
  },
  {
    albumName: "HUNNID: GATEKEEPING",
    artist: "xxxmanera",
    genre: "хип-хоп;рэп;rage",
    country: "Россия",
    yandexMusicPlays: 182407,
    soundcloudPlays: 325111,
    rhymesImages: 5,
    structureRhythm: 0,
    styleImplementation: 5,
    individualityCharisma: 5,
    atmosphereVibe: 7
  },
  {
    albumName: "exxxtract vol. 1",
    artist: "xxxmanera",
    genre: "хип-хоп;рэп;rage",
    country: "Россия",
    yandexMusicPlays: 232476,
    soundcloudPlays: 381281,
    rhymesImages: 3,
    structureRhythm: 8,
    styleImplementation: 10,
    individualityCharisma: 4,
    atmosphereVibe: 0
  },
  {
    albumName: "Project V",
    artist: "Voskresenskii",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 486839,
    soundcloudPlays: 125536,
    rhymesImages: 1,
    structureRhythm: 3,
    styleImplementation: 4,
    individualityCharisma: 4,
    atmosphereVibe: 7
  },
  {
    albumName: "Как испортить вечеринку?",
    artist: "CUPSIZE",
    genre: "гранж;рок",
    country: "Россия",
    yandexMusicPlays: 418420,
    soundcloudPlays: 493171,
    rhymesImages: 2,
    structureRhythm: 4,
    styleImplementation: 10,
    individualityCharisma: 3,
    atmosphereVibe: 2
  },
  {
    albumName: "… меня малышка",
    artist: "CUPSIZE",
    genre: "гранж;рок;hyperpop",
    country: "Россия",
    yandexMusicPlays: 327495,
    soundcloudPlays: 171425,
    rhymesImages: 8,
    structureRhythm: 10,
    styleImplementation: 8,
    individualityCharisma: 10,
    atmosphereVibe: 6
  },
  {
    albumName: "дели на два",
    artist: "CUPSIZE",
    genre: "гранж;рок",
    country: "Россия",
    yandexMusicPlays: 474537,
    soundcloudPlays: 247341,
    rhymesImages: 3,
    structureRhythm: 6,
    styleImplementation: 3,
    individualityCharisma: 7,
    atmosphereVibe: 7
  },
  {
    albumName: "кажется, в аду прикольно, но меня выгнали б утром",
    artist: "CUPSIZE",
    genre: "гранж;рок",
    country: "Россия",
    yandexMusicPlays: 42407,
    soundcloudPlays: 335333,
    rhymesImages: 2,
    structureRhythm: 1,
    styleImplementation: 8,
    individualityCharisma: 2,
    atmosphereVibe: 1
  },
  {
    albumName: "в моих легких выросли цветы",
    artist: "CUPSIZE",
    genre: "гранж;рок",
    country: "Россия",
    yandexMusicPlays: 277241,
    soundcloudPlays: 81121,
    rhymesImages: 0,
    structureRhythm: 3,
    styleImplementation: 8,
    individualityCharisma: 8,
    atmosphereVibe: 9
  },
  {
    albumName: "неуравновешеннолетние песни pt.1",
    artist: "CUPSIZE",
    genre: "гранж;рок",
    country: "Россия",
    yandexMusicPlays: 21271,
    soundcloudPlays: 445609,
    rhymesImages: 7,
    structureRhythm: 4,
    styleImplementation: 4,
    individualityCharisma: 6,
    atmosphereVibe: 4
  },
  {
    albumName: "заставь меня плакать",
    artist: "CUPSIZE",
    genre: "гранж;рок",
    country: "Россия",
    yandexMusicPlays: 486121,
    soundcloudPlays: 493301,
    rhymesImages: 9,
    structureRhythm: 3,
    styleImplementation: 5,
    individualityCharisma: 4,
    atmosphereVibe: 2
  },
  {
    albumName: "последние песни про женщин",
    artist: "рэйчи",
    genre: "гранж;рок",
    country: "Россия",
    yandexMusicPlays: 165686,
    soundcloudPlays: 37354,
    rhymesImages: 10,
    structureRhythm: 0,
    styleImplementation: 8,
    individualityCharisma: 2,
    atmosphereVibe: 10
  },
  {
    albumName: "ВЫСШАЯ ШКОЛА БИЗНЕСА",
    artist: "GRILLYAZH",
    genre: "поп",
    country: "Россия",
    yandexMusicPlays: 150934,
    soundcloudPlays: 483508,
    rhymesImages: 9,
    structureRhythm: 0,
    styleImplementation: 8,
    individualityCharisma: 8,
    atmosphereVibe: 8
  },
  {
    albumName: "WILD EA$T",
    artist: "Saluki",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 209182,
    soundcloudPlays: 25176,
    rhymesImages: 5,
    structureRhythm: 4,
    styleImplementation: 6,
    individualityCharisma: 6,
    atmosphereVibe: 5
  },
  {
    albumName: "BOLSHIE KURTKI",
    artist: "Saluki",
    genre: "хип-хоп;рэп",
    country: "Россия",
    yandexMusicPlays: 156107,
    soundcloudPlays: 301136,
    rhymesImages: 9,
    structureRhythm: 1,
    styleImplementation: 0,
    individualityCharisma: 2,
    atmosphereVibe: 5
  }
];

export { type TAlbum, albums };
